{
 "title": "Go App Monitoring",
 "tags": [
  "go",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Requests per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(myapp_http_requests_total[1m])",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Average Response Time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(myapp_http_request_duration_seconds_sum[1m]) / rate(myapp_http_request_duration_seconds_count[1m])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(myapp_http_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p95 {{endpoint}}"
    }
   ]
  },
  {
   "title": "Total Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (method) (myapp_http_requests_total)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}